// Static mock data for the app — in a real app this would come from an API

export const BANKS = [
  "Access Bank","First Bank","GT Bank","UBA","Zenith Bank","Fidelity Bank",
  "FCMB","Sterling Bank","Stanbic IBTC","Wema Bank","Polaris Bank",
  "Union Bank","Ecobank","Keystone Bank","Heritage Bank",
];

export const INVESTMENTS = [
  {id:1,name:"Maitama Residency",loc:"FCT Abuja",type:"Residential",equity:"10%",monthly:"₦18,500",funded:100,col:"#A0522D",spv:"PropVest Maitama Ltd",lockEnd:"15 Nov 2028",canTrigger:false,voteActive:true,voteFor:2,voteAgainst:1,voteTotal:10,myVote:null,currentVal:13920000,gain:"+16.0%",myInvested:12000000,totalPropValue:120000000,purchasePropValue:103000000,purchaseDate:"15 Nov 2022",slots:1,totalSlots:10,incomeType:"rental",monthlyRental:18500,holdYears:3,saleEligibleDate:"15 Nov 2025"},
  {id:2,name:"Victoria Island Apt",loc:"Lagos Island",type:"Apartment",equity:"10%",monthly:"₦24,000",funded:100,col:"#7A3B1E",spv:"PropVest VI Apt Ltd",lockEnd:"02 Jan 2027",canTrigger:false,voteActive:false,voteFor:0,voteAgainst:0,voteTotal:10,myVote:null,currentVal:9095000,gain:"+7.0%",myInvested:8500000,totalPropValue:85000000,purchasePropValue:79500000,purchaseDate:"02 Jan 2024",slots:1,totalSlots:10,incomeType:"rental",monthlyRental:24000,holdYears:3,saleEligibleDate:"02 Jan 2027"},
  {id:3,name:"Lekki Land Plot",loc:"Lekki, Lagos",type:"Land",equity:"10%",monthly:"Capital",funded:80,col:"#40916C",spv:"PropVest Lekki Land Ltd",lockEnd:"20 Jan 2026",canTrigger:true,voteActive:false,voteFor:0,voteAgainst:0,voteTotal:10,myVote:null,currentVal:5468000,gain:"+36.7%",myInvested:4000000,totalPropValue:40000000,purchasePropValue:29200000,purchaseDate:"20 Jan 2023",slots:1,totalSlots:10,incomeType:"resale",monthlyRental:0,holdYears:3},
];

export const OFF_PLAN = [
  {id:1,name:"Katampe Extension Villa",loc:"FCT Abuja",type:"4-Bed Detached",price:45000000,stage:"Foundation",completion:"Q4 2027",developer:"Sunrise Properties Ltd",downPct:20,plans:[{id:"6m",label:"6 Months",months:6,rate:0},{id:"12m",label:"12 Months",months:12,rate:3},{id:"24m",label:"24 Months",months:24,rate:6},{id:"36m",label:"36 Months",months:36,rate:9}],features:["Smart Home","Solar Panels","BQ Quarters","2 Parking","Estate Security"],img:"🏡",renders:[{view:"Exterior",label:"Front Elevation",desc:"4-bed detached with double garage, large compound and BQ quarters",col:"#A0522D",accent:"#C4956A",shape:"detached"},{view:"Interior",label:"Living Room",desc:"Open plan living area, 18ft ceiling, imported marble tiles",col:"#7A3B1E",accent:"#B8AFA6",shape:"interior"},{view:"Floor Plan",label:"Ground Floor",desc:"Living, dining, kitchen, guest room, 2 en-suite masters on first floor",col:"#1A2A1A",accent:"#52B788",shape:"floorplan"}],finishTypes:[{id:"carcass",label:"Carcass",price:45000000,desc:"Structural shell only. Walls, roof, windows & doors. No interior finishes, tiling or fittings.",includes:["Structural walls & columns","Roof & fascia boards","Electrical & plumbing rough-in"]},{id:"semi",label:"Semi-Finished",price:52000000,desc:"Carcass plus internal plastering, electrical wiring and plumbing piping.",includes:["All Carcass inclusions","Internal plastering","External doors (steel)","Window frames & louvres","Outside painting","Electrical wiring (conduits & cables)","Plumbing piping (water supply & drainage)"]},{id:"full",label:"Fully Finished",price:62000000,desc:"Turnkey, move-in ready. All premium fittings, kitchen cabinets, wardrobes and painting included.",includes:["All Semi-Finished inclusions","Electrical fittings (sockets, switches & fixtures)","Plumbing fittings (WC, basin, taps & shower)","Floor & wall tiling (premium)","POP ceiling","Premium kitchen cabinets & countertop","Built-in wardrobes","Skim coat & painting (2 coats)","Landscaping & compound paving"]}]},
  {id:2,name:"Lekki Phase 2 Apartments",loc:"Lekki, Lagos",type:"2-Bed Apartment",price:22000000,stage:"Superstructure",completion:"Q2 2027",developer:"Coastline Homes Ltd",downPct:15,plans:[{id:"6m",label:"6 Months",months:6,rate:0},{id:"12m",label:"12 Months",months:12,rate:2.5},{id:"18m",label:"18 Months",months:18,rate:5},{id:"24m",label:"24 Months",months:24,rate:7}],features:["Swimming Pool","Gym","24hr Power","CCTV","Concierge"],img:"🏢",renders:[{view:"Exterior",label:"Building Facade",desc:"Modern apartment block with glass balconies, swimming pool on podium",col:"#0F4C5C",accent:"#22D3EE",shape:"apartment"},{view:"Interior",label:"Sample Unit",desc:"2-bed apartment with open kitchen, floor-to-ceiling windows",col:"#1A1A2E",accent:"#A5B4FC",shape:"interior"},{view:"Floor Plan",label:"Unit Layout",desc:"Open plan living, 2 bedrooms, 2 bathrooms, balcony",col:"#1A2A1A",accent:"#52B788",shape:"floorplan"}],finishTypes:[{id:"carcass",label:"Carcass",price:22000000,desc:"Structural shell with windows, external doors and rough-in services only.",includes:["Structural walls","Roof slab","Electrical & plumbing rough-in"]},{id:"semi",label:"Semi-Finished",price:26500000,desc:"Carcass plus internal plastering, electrical wiring and plumbing piping.",includes:["All Carcass inclusions","Internal plastering","External doors (steel)","Window frames & louvres","Outside painting","Electrical wiring (conduits & cables)","Plumbing piping (water supply & drainage)"]},{id:"full",label:"Fully Finished",price:32000000,desc:"Turnkey apartment ready for immediate occupation with all premium fittings.",includes:["All Semi-Finished inclusions","Electrical fittings (sockets, switches & fixtures)","Plumbing fittings (WC, basin, taps & shower)","Floor & wall tiling (premium)","POP ceiling","Kitchen cabinets & countertop","Built-in wardrobes","Full painting"]}]},
  {id:3,name:"Asokoro Terraces",loc:"FCT Abuja",type:"3-Bed Terrace",price:32000000,stage:"Roofing",completion:"Q1 2027",developer:"Capitol Developers Ltd",downPct:25,plans:[{id:"6m",label:"6 Months",months:6,rate:0},{id:"12m",label:"12 Months",months:12,rate:3},{id:"18m",label:"18 Months",months:18,rate:5.5}],features:["Serviced Estate","Fitted Kitchen","BQ","Green Areas","CCTV"],img:"🏘",renders:[{view:"Exterior",label:"Street View",desc:"Row of 3-bed terraces with gated estate, green areas and CCTV",col:"#3A2A1A",accent:"#C4956A",shape:"terrace"},{view:"Interior",label:"Master Bedroom",desc:"En-suite master with fitted wardrobe, large windows",col:"#1A1A1A",accent:"#B8AFA6",shape:"interior"},{view:"Floor Plan",label:"Floor Layout",desc:"3 beds, 3 baths, study, open plan ground floor, BQ",col:"#1A2A1A",accent:"#52B788",shape:"floorplan"}],finishTypes:[{id:"carcass",label:"Carcass",price:32000000,desc:"Shell structure including walls, roof, windows and rough mechanical installations.",includes:["Structural walls & columns","Roof structure & tiles","Electrical & plumbing rough-in"]},{id:"semi",label:"Semi-Finished",price:38000000,desc:"Carcass plus internal plastering, electrical wiring and plumbing piping.",includes:["All Carcass inclusions","Internal plastering","External doors (steel)","Window frames & louvres","Outside painting","Electrical wiring (conduits & cables)","Plumbing piping (water supply & drainage)","BQ finishing"]},{id:"full",label:"Fully Finished",price:46500000,desc:"Move-in ready with kitchen fittings, wardrobes, full painting and all appliance connections.",includes:["All Semi-Finished inclusions","Electrical fittings (sockets, switches & fixtures)","Plumbing fittings (WC, basin, taps & shower)","Floor & wall tiling (premium)","POP ceiling","Kitchen cabinets & fitted appliances","Built-in wardrobes (all beds)","Full interior painting","Paved compound & landscaping"]}]},
];

export const DEV_PROPS = [
  {id:1,name:"Maitama Residency",spv:"PropVest Maitama Ltd",status:"LIVE",target:120000000,pooled:84000000,investors:14,monthly_rent:2600000,distributed:2340000,occupancy:"Occupied",location:"FCT Abuja",type:"Residential",subscribers:[{id:"USR-001",name:"A. Okonkwo",stake:"4.17%",amount:"₦5,000,000"},{id:"USR-002",name:"B. Fashola",stake:"8.33%",amount:"₦10,000,000"},{id:"USR-003",name:"C. Eze",stake:"6.25%",amount:"₦7,500,000"},{id:"USR-004",name:"D. Adesanya",stake:"4.17%",amount:"₦5,000,000"},{id:"USR-005",name:"E. Uchenna",stake:"4.17%",amount:"₦5,000,000"}]},
  {id:2,name:"Victoria Island Apt",spv:"PropVest VI Apt Ltd",status:"FUNDING",target:85000000,pooled:38250000,investors:22,monthly_rent:0,distributed:0,occupancy:"Pending",location:"Lagos Island",type:"Apartment",subscribers:[{id:"USR-015",name:"O. Adebayo",stake:"3.53%",amount:"₦3,000,000"},{id:"USR-016",name:"P. Chukwu",stake:"5.88%",amount:"₦5,000,000"}]},
];

export const HISTORY = [
  {date:"14 Feb 2026",prop:"Maitama Residency",gross:"₦20,556",net:"₦18,500"},
  {date:"14 Feb 2026",prop:"Victoria Island Apt",gross:"₦26,667",net:"₦24,000"},
  {date:"14 Jan 2026",prop:"Maitama Residency",gross:"₦20,556",net:"₦18,500"},
  {date:"14 Jan 2026",prop:"Victoria Island Apt",gross:"₦26,667",net:"₦24,000"},
  {date:"14 Dec 2025",prop:"Maitama Residency",gross:"₦20,556",net:"₦18,500"},
];
